### ISSUE TITLE
Wrong Theme in Java Project Manager Setting Page

### ISSUE THREAD

**Issue by mtptb** [Drkryz/vscode-drkcolor-theme#1]
Hello Drkryz,

I discovered a problem with your theme color.
I work with VSCode on Java projects and when I launch "Configure Java Runtime" from command palette, I can't see the setting page correctly. If I restore VSCode Default Theme or set another theme VSCode work properly.
I've attached my screens below.
You can reproduce it installing Java Project Manager extension and then launching _"Configure Java Runtime"_ in command palette meanwhile your theme color is applied:
>_Name: Project Manager for Java
Id: vscjava.vscode-java-dependency
Description: Manage Java projects in Visual Studio Code
Version: 0.18.8
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-dependency_

![image](https://user-images.githubusercontent.com/39939267/143445711-45132380-2eef-41fd-81fa-0d3663c23981.png)

![image](https://user-images.githubusercontent.com/39939267/143445643-4923e2bb-7728-4c7d-964f-b4e32df57ad0.png)

Thanks for your theme color!!
Good luck

**Comment by cainhooow** [comment]
Hi, thanks for your report and we apologize for the delay in responding, we are already working on a fix for this bug, and thanks again.

**Comment by cainhooow** [comment]
> Hello Drkryz,
> 
> I discovered a problem with your theme color. I work with VSCode on Java projects and when I launch "Configure Java Runtime" from command palette, I can't see the setting page correctly. If I restore VSCode Default Theme or set another theme VSCode work properly. I've attached my screens below. You can reproduce it installing Java Project Manager extension and then launching _"Configure Java Runtime"_ in command palette meanwhile your theme color is applied:
> 
> > _Name: Project Manager for Java
> > Id: vscjava.vscode-java-dependency
> > Description: Manage Java projects in Visual Studio Code
> > Version: 0.18.8
> > Publisher: Microsoft
> > VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-dependency_
> 
> ![image](https://user-images.githubusercontent.com/39939267/143445711-45132380-2eef-41fd-81fa-0d3663c23981.png)
> 
> ![image](https://user-images.githubusercontent.com/39939267/143445643-4923e2bb-7728-4c7d-964f-b4e32df57ad0.png)
> 
> Thanks for your theme color!! Good luck

Hello, we analyzed and corrected some things in the theme, and apparently the problem was fixed, we did all the necessary tests and there was no more problem with the extension. Thanks for the report! 🤗
